drop table if exists screening_results;

create table screening_results (
   id                      INTEGER PRIMARY KEY
  ,diagnosis               VARCHAR(1)
  ,radius_mean             NUMERIC(5,3)
  ,texture_mean            NUMERIC(5,2)
  ,perimeter_mean          NUMERIC(5,2)
  ,area_mean               NUMERIC(5,1)
  ,smoothness_mean         NUMERIC(7,5)
  ,compactness_mean        NUMERIC(7,5)
  ,concavity_mean          NUMERIC(9,7)
  ,concave_points_mean     NUMERIC(8,6)
  ,symmetry_mean           NUMERIC(6,4)
  ,fractal_dimension_mean  NUMERIC(7,5)
  ,radius_se               NUMERIC(6,4)
  ,texture_se              NUMERIC(6,4)
  ,perimeter_se            NUMERIC(6,4)
  ,area_se                 NUMERIC(6,3)
  ,smoothness_se           NUMERIC(8,6)
  ,compactness_se          NUMERIC(8,6)
  ,concavity_se            NUMERIC(9,7)
  ,concave_points_se       NUMERIC(8,6)
  ,symmetry_se             NUMERIC(8,6)
  ,fractal_dimension_se    NUMERIC(9,7)
  ,radius_worst            NUMERIC(5,3)
  ,texture_worst           NUMERIC(5,2)
  ,perimeter_worst         NUMERIC(5,2)
  ,area_worst              NUMERIC(5,1)
  ,smoothness_worst        NUMERIC(7,5)
  ,compactness_worst       NUMERIC(7,5)
  ,concavity_worst         NUMERIC(8,6)
  ,concave_points_worst    NUMERIC(8,6)
  ,symmetry_worst          NUMERIC(6,4)
  ,fractal_dimension_worst NUMERIC(7,5)
  ,group_id                VARCHAR(1)
);